package com.Srijan.BirdSpecies_Classification.ui.home;

import com.Srijan.BirdSpecies_Classification.R;

public class BirdData {
    public static String[] title = new String[] {
            "ALBATROSS",
            "ALEXANDRINE PARAKEET",
            "AMERICAN REDSTART",
            "ANNAS HUMMINGBIRD",
            "ANTBIRD",
            "ARARIPE MANAKIN",
            "BALI STARLING",
            "BALTIMORE ORIOLE",
            "BANDED BROADBILL",
            "BARN OWL",
            "BARRED PUFFBIRD",
            "BAY-BREASTED WARBLER",
            "BELTED KINGFISHER",
            "BIRD OF PARADISE",
            "BLACK-CAPPED CHICKADEE",
            "BLACK-NECKED GREBE",
            "BLACK FRANCOLIN",
            "BLACK SKIMMER",
            "BLACK VULTURE",
            "BLUE GROUSE",
            "BOBOLINK",
            "BROWN NOODY",
            "BROWN THRASHER",
            "CALIFORNIA CONDOR",
            "CAPUCHINBIRD",
            "CASPIAN TERN",
            "CASSOWARY",
            "CHUKAR PARTRIDGE",
            "CINNAMON TEAL",
            "COCKATOO",
            "COMMON FIRECREST",
            "COMMON HOUSE MARTIN",
            "COMMON LOON",
            "COMMON POORWILL",
            "COUCHS KINGBIRD",
            "CRESTED AUKLET",
            "CRESTED NUTHATCH",
            "CROW",
            "CROWNED PIGEON",
            "D-ARNAUDS BARBET",
            "DARK EYED JUNCO",
            "DOWNY WOODPECKER",
            "EASTERN MEADOWLARK",
            "EASTERN TOWEE",
            "ELEGANT TROGON",
            "ELLIOTS  PHEASANT",
            "EMPEROR PENGUIN",
            "EURASIAN MAGPIE",
            "EVENING GROSBEAK",
            "FIRE TAILLED MYZORNIS",
            "FLAMINGO",
            "GILDED FLICKER",
            "GLOSSY IBIS",
            "GO AWAY BIRD",
            "GOLD WING WARBLER",
            "GOLDEN CHEEKED WARBLER",
            "GOLDEN EAGLE",
            "GOLDEN PHEASANT",
            "GOULDIAN FINCH",
            "GRAY PARTRIDGE",
            "GREAT POTOO",
            "GREEN JAY",
            "HARPY EAGLE",
            "HAWAIIAN GOOSE",
            "HELMET VANGA",
            "HOATZIN",
            "HOODED MERGANSER",
            "HOOPOES",
            "HORNED GUAN",
            "HOUSE FINCH",
            "HOUSE SPARROW",
            "INDIAN BUSTARD",
            "INDIAN PITTA",
            "INDIGO BUNTING",
            "JABIRU",
            "JAVA SPARROW",
            "JAVAN MAGPIE",
            "KAKAPO",
            "KILLDEAR",
            "KING VULTURE",
            "KIWI",
            "MALEO",
            "MANDRIN DUCK",
            "MARABOU STORK",
            "MASKED BOOBY",
            "MIKADO  PHEASANT",
            "MOURNING DOVE",
            "MYNA",
            "NICOBAR PIGEON",
            "NORTHERN BALD IBIS",
            "NORTHERN CARDINAL",
            "NORTHERN FLICKER",
            "NORTHERN JACANA",
            "NORTHERN PARULA",
            "OCELLATED TURKEY",
            "OKINAWA RAIL",
            "OSPREY",
            "OYSTER CATCHER",
            "PARUS MAJOR",
            "PELICAN",
            "PHILIPPINE EAGLE",
            "PINK ROBIN",
            "PURPLE FINCH",
            "PURPLE MARTIN",
            "PURPLE SWAMPHEN",
            "RAZORBILL",
            "RED BEARDED BEE EATER",
            "RED BELLIED PITTA",
            "RED FACED WARBLER",
            "RED WINGED BLACKBIRD",
            "RING-NECKED PHEASANT",
            "ROBIN",
            "ROSY FACED LOVEBIRD",
            "RUFOUS KINGFISHER",
            "SAMATRAN THRUSH",
            "SCARLET MACAW",
            "SHOEBILL",
            "SMITHS LONGSPUR",
            "SNOWY EGRET",
            "SNOWY OWL",
            "SORA",
            "SPLENDID WREN",
            "SPOON BILED SANDPIPER",
            "SPOONBILL",
            "SRI LANKA BLUE MAGPIE",
            "STORK BILLED KINGFISHER",
            "STRAWBERRY FINCH",
            "SUPERB STARLING",
            "SWINHOES PHEASANT",
            "TAIWAN MAGPIE",
            "TAKAHE",
            "TASMANIAN HEN",
            "TEAL DUCK",
            "TIT MOUSE",
            "TOWNSENDS WARBLER",
            "TREE SWALLOW",
            "TRUMPTER SWAN",
            "TURKEY VULTURE",
            "UMBRELLA BIRD",
            "VARIED THRUSH",
            "VENEZUELIAN TROUPIAL",
            "VERMILION FLYCATHER",
            "VIOLET GREEN SWALLOW",
            "WATTLED CURASSOW",
            "WHIMBREL",
            "WHITE CHEEKED TURACO",
            "WHITE NECKED RAVEN",
            "WHITE TAILED TROPIC",
            "WILD TURKEY",
            "WILSONS BIRD OF PARADISE",
            "WOOD DUCK",
            "YELLOW CACIQUE",
    };
    public static int[] picturePath =new int[] {
            R.drawable.albatross,
            R.drawable.alexandrine_parakeet,
            R.drawable.american_redstart,
            R.drawable.annas_hummingbird,
            R.drawable.antbird,
            R.drawable.araripe_manakin,
            R.drawable.bali_starling,
            R.drawable.baltimore_oriole,
            R.drawable.banded_broadbill,
            R.drawable.barn_owl,
            R.drawable.barred_puffbird,
            R.drawable.bay_breasted_warbler,
            R.drawable.belted_kingfisher,
            R.drawable.bird_of_paradise,
            R.drawable.black_capped_chickadee,
            R.drawable.black_necked_grebe,
            R.drawable.black_francolin,
            R.drawable.black_skimmer,
            R.drawable.black_vulture,
            R.drawable.blue_grouse,
            R.drawable.bobolink,
            R.drawable.brown_noody,
            R.drawable.brown_thrasher,
            R.drawable.california_condor,
            R.drawable.capuchinbird,
            R.drawable.caspian_tern,
            R.drawable.cassowary,
            R.drawable.chukar_partridge,
            R.drawable.cinnamon_teal,
            R.drawable.cockatoo,
            R.drawable.common_firecrest,
            R.drawable.common_house_martin,
            R.drawable.common_loon,
            R.drawable.common_poorwill,
            R.drawable.couchs_kingbird,
            R.drawable.crested_auklet,
            R.drawable.crested_nuthatch,
            R.drawable.crow,
            R.drawable.crowned_pigeon,
            R.drawable.d_arnauds_barbet,
            R.drawable.dark_eyed_junco,
            R.drawable.downy_woodpecker,
            R.drawable.eastern_meadowlark,
            R.drawable.eastern_towee,
            R.drawable.elegant_trogon,
            R.drawable.elliots__pheasant,
            R.drawable.emperor_penguin,
            R.drawable.eurasian_magpie,
            R.drawable.evening_grosbeak,
            R.drawable.fire_tailled_myzornis,
            R.drawable.flamingo,
            R.drawable.gilded_flicker,
            R.drawable.glossy_ibis,
            R.drawable.go_away_bird,
            R.drawable.gold_wing_warbler,
            R.drawable.golden_cheeked_warbler,
            R.drawable.golden_eagle,
            R.drawable.golden_pheasant,
            R.drawable.gouldian_finch,
            R.drawable.gray_partridge,
            R.drawable.great_potoo,
            R.drawable.green_jay,
            R.drawable.harpy_eagle,
            R.drawable.hawaiian_goose,
            R.drawable.helmet_vanga,
            R.drawable.hoatzin,
            R.drawable.hooded_merganser,
            R.drawable.hoopoes,
            R.drawable.horned_guan,
            R.drawable.house_finch,
            R.drawable.house_sparrow,
            R.drawable.indian_bustard,
            R.drawable.indian_pitta,
            R.drawable.indigo_bunting,
            R.drawable.jabiru,
            R.drawable.java_sparrow,
            R.drawable.javan_magpie,
            R.drawable.kakapo,
            R.drawable.killdear,
            R.drawable.king_vulture,
            R.drawable.kiwi,
            R.drawable.maleo,
            R.drawable.mandrin_duck,
            R.drawable.marabou_stork,
            R.drawable.masked_booby,
            R.drawable.mikado__pheasant,
            R.drawable.mourning_dove,
            R.drawable.myna,
            R.drawable.nicobar_pigeon,
            R.drawable.northern_bald_ibis,
            R.drawable.northern_cardinal,
            R.drawable.northern_flicker,
            R.drawable.northern_jacana,
            R.drawable.northern_parula,
            R.drawable.ocellated_turkey,
            R.drawable.okinawa_rail,
            R.drawable.osprey,
            R.drawable.oyster_catcher,
            R.drawable.parus_major,
            R.drawable.pelican,
            R.drawable.philippine_eagle,
            R.drawable.pink_robin,
            R.drawable.purple_finch,
            R.drawable.purple_martin,
            R.drawable.purple_swamphen,
            R.drawable.razorbill,
            R.drawable.red_bearded_bee_eater,
            R.drawable.red_bellied_pitta,
            R.drawable.red_faced_warbler,
            R.drawable.red_winged_blackbird,
            R.drawable.ring_necked_pheasant,
            R.drawable.robin,
            R.drawable.rosy_faced_lovebird,
            R.drawable.rufous_kingfisher,
            R.drawable.samatran_thrush,
            R.drawable.scarlet_macaw,
            R.drawable.shoebill,
            R.drawable.smiths_longspur,
            R.drawable.snowy_egret,
            R.drawable.snowy_owl,
            R.drawable.sora,
            R.drawable.splendid_wren,
            R.drawable.spoon_biled_sandpiper,
            R.drawable.spoonbill,
            R.drawable.sri_lanka_blue_magpie,
            R.drawable.stork_billed_kingfisher,
            R.drawable.strawberry_finch,
            R.drawable.superb_starling,
            R.drawable.swinhoes_pheasant,
            R.drawable.taiwan_magpie,
            R.drawable.takahe,
            R.drawable.tasmanian_hen,
            R.drawable.teal_duck,
            R.drawable.tit_mouse,
            R.drawable.townsends_warbler,
            R.drawable.tree_swallow,
            R.drawable.trumpter_swan,
            R.drawable.turkey_vulture,
            R.drawable.umbrella_bird,
            R.drawable.varied_thrush,
            R.drawable.venezuelian_troupial,
            R.drawable.vermilion_flycather,
            R.drawable.violet_green_swallow,
            R.drawable.wattled_curassow,
            R.drawable.whimbrel,
            R.drawable.white_cheeked_turaco,
            R.drawable.white_necked_raven,
            R.drawable.white_tailed_tropic,
            R.drawable.wild_turkey,
            R.drawable.wilsons_bird_of_paradise,
            R.drawable.wood_duck,
            R.drawable.yellow_cacique
    };
}
